// ─── MBTI Personality Type Descriptions ─────────────────────────────────────
// Complete data for all 16 types in EN + AR

import type { MBTIType } from "@/types";

export interface PersonalityInfo {
  type: MBTIType;
  name_en: string;
  name_ar: string;
  tagline_en: string;
  tagline_ar: string;
  description_en: string;
  description_ar: string;
  strengths_en: string[];
  strengths_ar: string[];
  weaknesses_en: string[];
  weaknesses_ar: string[];
  careers_en: string[];
  careers_ar: string[];
  famous_en: string[];
  color: string;
  emoji: string;
}

export const personalities: Record<MBTIType, PersonalityInfo> = {
  INTJ: {
    type: "INTJ",
    name_en: "The Architect",
    name_ar: "المعماري",
    tagline_en: "Imaginative and strategic thinkers",
    tagline_ar: "مفكرون خياليون واستراتيجيون",
    description_en: "INTJs are analytical problem-solvers, driven by perfection and the desire to implement their ideas. They are independent, decisive, and always looking to understand the complex systems of the world.",
    description_ar: "المعماريون محللون يحلون المشكلات، مدفوعون بالكمالية والرغبة في تنفيذ أفكارهم. إنهم مستقلون وحاسمون ودائمًا يسعون لفهم الأنظمة المعقدة في العالم.",
    strengths_en: ["Strategic thinking", "High intelligence", "Determined & self-confident", "Open to learning", "Hard-working"],
    strengths_ar: ["التفكير الاستراتيجي", "الذكاء العالي", "محدد وواثق بالنفس", "منفتح على التعلم", "مجتهد"],
    weaknesses_en: ["Arrogant", "Dismissive of emotions", "Overly critical", "Impatient", "Difficulty with social interaction"],
    weaknesses_ar: ["متغطرس", "يتجاهل المشاعر", "ناقد بشكل مفرط", "نفاد صبر", "صعوبة في التفاعل الاجتماعي"],
    careers_en: ["Software Architect", "Data Scientist", "Strategic Planner", "Investment Banker", "Researcher"],
    careers_ar: ["مهندس معماري للبرمجيات", "عالم بيانات", "مخطط استراتيجي", "مصرفي استثماري", "باحث"],
    famous_en: ["Elon Musk", "Mark Zuckerberg", "Stephen Hawking"],
    color: "#6C63FF",
    emoji: "🏛️",
  },
  INTP: {
    type: "INTP",
    name_en: "The Logician",
    name_ar: "المنطقي",
    tagline_en: "Innovative inventors with an unquenchable thirst for knowledge",
    tagline_ar: "مبتكرون بعطش لا ينطفئ للمعرفة",
    description_en: "INTPs are passionate about theory and abstract thinking. They're the quintessential problem-solvers who thrive on complexity and analysis.",
    description_ar: "المنطقيون شغوفون بالنظرية والتفكير المجرد. إنهم أمثلة المشكلات المثالية الذين يزدهرون بالتعقيد والتحليل.",
    strengths_en: ["Analytical", "Creative", "Open-minded", "Objective", "Enthusiastic"],
    strengths_ar: ["تحليلي", "مبدع", "منفتح الذهن", "موضوعي", "متحمس"],
    weaknesses_en: ["Insensitive", "Absent-minded", "Condescending", "Loathes rules", "Anxious"],
    weaknesses_ar: ["غير حساس", "شارد الذهن", "متعجرف", "يكره القواعد", "قلق"],
    careers_en: ["Mathematician", "Philosopher", "Systems Analyst", "Programmer", "Academic Researcher"],
    careers_ar: ["رياضي", "فيلسوف", "محلل أنظمة", "مبرمج", "باحث أكاديمي"],
    famous_en: ["Albert Einstein", "Charles Darwin", "Bill Gates"],
    color: "#5A52E0",
    emoji: "🔬",
  },
  ENTJ: {
    type: "ENTJ",
    name_en: "The Commander",
    name_ar: "القائد",
    tagline_en: "Bold, imaginative and strong-willed leaders",
    tagline_ar: "قادة جريئون وخياليون وقوة الإرادة",
    description_en: "ENTJs are natural-born leaders. They embody the drive and determination of a strong character, channeling it into strategies and plans to achieve their goals.",
    description_ar: "القادة قادة بالفطرة. إنهم يجسدون الدافع والتصميم لشخصية قوية، ويوجهونهما نحو استراتيجيات وخطط لتحقيق أهدافهم.",
    strengths_en: ["Efficient", "Energetic", "Self-confident", "Strong-willed", "Strategic thinker"],
    strengths_ar: ["كفء", "نشيط", "واثق بنفسه", "قوي الإرادة", "مفكر استراتيجي"],
    weaknesses_en: ["Stubborn", "Dominant", "Intolerant", "Cold and ruthless", "Impatient"],
    weaknesses_ar: ["عنيد", "مسيطر", "متعصب", "بارد وقاسٍ", "نفاد صبر"],
    careers_en: ["CEO", "Lawyer", "Manager", "Entrepreneur", "Judge"],
    careers_ar: ["رئيس تنفيذي", "محامي", "مدير", "رائد أعمال", "قاضي"],
    famous_en: ["Steve Jobs", "Margaret Thatcher", "Napoleon Bonaparte"],
    color: "#FF6584",
    emoji: "⚡",
  },
  ENTP: {
    type: "ENTP",
    name_en: "The Debater",
    name_ar: "المناظر",
    tagline_en: "Smart and curious thinkers who cannot resist an intellectual challenge",
    tagline_ar: "مفكرون أذكياء وفضوليون لا يقاومون التحدي الفكري",
    description_en: "ENTPs are quick, ingenious, and outspoken, able to find an effective argument for anything.",
    description_ar: "المناظرون سريعون وبارعون وصريحون، قادرون على إيجاد حجة فعالة لأي شيء.",
    strengths_en: ["Knowledgeable", "Quick thinker", "Excellent brainstormer", "Charismatic", "Energetic"],
    strengths_ar: ["متعلم", "سريع التفكير", "ممتاز في العصف الذهني", "كاريزمي", "نشيط"],
    weaknesses_en: ["Very argumentative", "Insensitive", "Intolerant", "Can find it difficult to focus"],
    weaknesses_ar: ["جدلي للغاية", "غير حساس", "متعصب", "يجد صعوبة في التركيز"],
    careers_en: ["Entrepreneur", "Lawyer", "Creative Director", "Consultant", "Software Developer"],
    careers_ar: ["رائد أعمال", "محامي", "مدير إبداعي", "مستشار", "مطور برمجيات"],
    famous_en: ["Leonardo da Vinci", "Benjamin Franklin", "Sacha Baron Cohen"],
    color: "#00C9A7",
    emoji: "💡",
  },
  INFJ: {
    type: "INFJ",
    name_en: "The Advocate",
    name_ar: "المناضل",
    tagline_en: "Quiet and mystical, yet very inspiring and tireless idealists",
    tagline_ar: "هادئ وغامض، لكنه ملهم وغير متعب من المثاليين",
    description_en: "INFJs are idealists who lead with deep moral convictions and creative vision. They are insightful, principled, and passionate about making a difference.",
    description_ar: "المناضلون مثاليون يقودون بقناعات أخلاقية عميقة ورؤية إبداعية. إنهم ثاقبون ومبدئيون وشغوفون بإحداث فرق.",
    strengths_en: ["Creative", "Insightful", "Principled", "Passionate", "Altruistic"],
    strengths_ar: ["مبدع", "ثاقب البصيرة", "مبدئي", "شغوف", "إيثاري"],
    weaknesses_en: ["Sensitive to criticism", "Reluctant to open up", "Perfectionistic", "Burnout-prone"],
    weaknesses_ar: ["حساس للنقد", "متحفظ في الانفتاح", "كمالي", "عرضة للإرهاق"],
    careers_en: ["Psychologist", "Writer", "Social Worker", "Teacher", "Counselor"],
    careers_ar: ["طبيب نفسي", "كاتب", "أخصائي اجتماعي", "معلم", "مستشار"],
    famous_en: ["Martin Luther King Jr.", "Nelson Mandela", "Oprah Winfrey"],
    color: "#8B85FF",
    emoji: "🌟",
  },
  INFP: {
    type: "INFP",
    name_en: "The Mediator",
    name_ar: "الوسيط",
    tagline_en: "Poetic, kind and altruistic people, eager to help a good cause",
    tagline_ar: "أشخاص شاعريون ولطيفون وإيثاريون، حريصون على مساعدة قضية نبيلة",
    description_en: "INFPs are creative, empathetic idealists guided by their core values. They are imaginative and often lost in their own world of possibility.",
    description_ar: "الوسطاء مبدعون ومتعاطفون ومثاليون يسترشدون بقيمهم الأساسية. إنهم متخيلون وغالبًا ما يكونون مفقودين في عالمهم الخاص من الإمكانيات.",
    strengths_en: ["Empathetic", "Creative", "Authentic", "Open-minded", "Passionate"],
    strengths_ar: ["متعاطف", "مبدع", "أصيل", "منفتح الذهن", "شغوف"],
    weaknesses_en: ["Unrealistic", "Self-isolating", "Difficult to know", "Takes things personally"],
    weaknesses_ar: ["غير واقعي", "يعزل نفسه", "صعب المعرفة", "يأخذ الأمور بشكل شخصي"],
    careers_en: ["Writer", "Artist", "Therapist", "Social Worker", "Musician"],
    careers_ar: ["كاتب", "فنان", "معالج نفسي", "أخصائي اجتماعي", "موسيقي"],
    famous_en: ["William Shakespeare", "J.R.R. Tolkien", "Johnny Depp"],
    color: "#FF9AA2",
    emoji: "🌸",
  },
  ENFJ: {
    type: "ENFJ",
    name_en: "The Protagonist",
    name_ar: "البطل",
    tagline_en: "Charismatic and inspiring leaders, able to mesmerize their listeners",
    tagline_ar: "قادة كاريزميون وملهمون قادرون على سحر مستمعيهم",
    description_en: "ENFJs are natural-born leaders, full of passion and charisma. They radiate authenticity, concern, and altruism.",
    description_ar: "الأبطال قادة بالفطرة، مليئون بالشغف والكاريزما. يشعون بالأصالة والاهتمام والإيثار.",
    strengths_en: ["Tolerant", "Reliable", "Charismatic", "Altruistic", "Natural leader"],
    strengths_ar: ["متسامح", "موثوق", "كاريزمي", "إيثاري", "قائد طبيعي"],
    weaknesses_en: ["Overly idealistic", "Too selfless", "Too sensitive", "Condescending"],
    weaknesses_ar: ["مثالي للغاية", "إيثاري أكثر من اللازم", "حساس للغاية", "متعجرف"],
    careers_en: ["Teacher", "Coach", "HR Manager", "Politician", "Counselor"],
    careers_ar: ["معلم", "مدرب", "مدير موارد بشرية", "سياسي", "مستشار"],
    famous_en: ["Barack Obama", "Oprah Winfrey", "Nelson Mandela"],
    color: "#6C63FF",
    emoji: "🎭",
  },
  ENFP: {
    type: "ENFP",
    name_en: "The Campaigner",
    name_ar: "الناشط",
    tagline_en: "Enthusiastic, creative and sociable free spirits",
    tagline_ar: "أرواح حرة متحمسة ومبدعة واجتماعية",
    description_en: "ENFPs are free spirits with an energetic and passionate love of life. They are creative, spontaneous, and always looking for connections.",
    description_ar: "الناشطون أرواح حرة ذات حب حياة نشط وشغوف. إنهم مبدعون وتلقائيون ودائمًا يبحثون عن الروابط.",
    strengths_en: ["Enthusiastic", "Creative", "Sociable", "Empathetic", "Good communicator"],
    strengths_ar: ["متحمس", "مبدع", "اجتماعي", "متعاطف", "متواصل جيد"],
    weaknesses_en: ["People-pleasing", "Easily stressed", "Highly emotional", "Overthinks"],
    weaknesses_ar: ["يسعى لإرضاء الآخرين", "يُجهَد بسهولة", "عاطفي للغاية", "يبالغ في التفكير"],
    careers_en: ["Journalist", "Psychologist", "Actor", "Designer", "Marketing Manager"],
    careers_ar: ["صحفي", "طبيب نفسي", "ممثل", "مصمم", "مدير تسويق"],
    famous_en: ["Robin Williams", "Walt Disney", "Ellen DeGeneres"],
    color: "#FFB347",
    emoji: "🦋",
  },
  ISTJ: {
    type: "ISTJ",
    name_en: "The Logistician",
    name_ar: "اللوجستي",
    tagline_en: "Practical and fact-minded individuals, whose reliability cannot be doubted",
    tagline_ar: "أفراد عمليون ذو عقلية واقعية، موثوقيتهم لا تقبل الشك",
    description_en: "ISTJs are responsible organizers, driven to create and enforce order within institutions and systems.",
    description_ar: "اللوجستيون منظمون مسؤولون، مدفوعون لإنشاء وتطبيق النظام داخل المؤسسات والأنظمة.",
    strengths_en: ["Responsible", "Thorough", "Dependable", "Calm and practical", "Honest"],
    strengths_ar: ["مسؤول", "شامل", "موثوق", "هادئ وعملي", "صادق"],
    weaknesses_en: ["Stubborn", "Insensitive", "Judgmental", "Always by the book"],
    weaknesses_ar: ["عنيد", "غير حساس", "يصدر الأحكام", "دائمًا وفق الكتاب"],
    careers_en: ["Accountant", "Military Officer", "Judge", "Project Manager", "Doctor"],
    careers_ar: ["محاسب", "ضابط عسكري", "قاضي", "مدير مشروع", "طبيب"],
    famous_en: ["George Washington", "Jeff Bezos", "Angela Merkel"],
    color: "#4A90D9",
    emoji: "📋",
  },
  ISFJ: {
    type: "ISFJ",
    name_en: "The Defender",
    name_ar: "المدافع",
    tagline_en: "Very dedicated and warm protectors, always ready to defend their loved ones",
    tagline_ar: "حماة متفانون ودافئون، دائمًا مستعدون للدفاع عن أحبائهم",
    description_en: "ISFJs are protectors who work tirelessly to ensure that others are taken care of. They are warm, caring, and highly dedicated.",
    description_ar: "المدافعون حماة يعملون بلا كلل لضمان الاهتمام بالآخرين. إنهم دافئون ومهتمون ومتفانون للغاية.",
    strengths_en: ["Supportive", "Reliable", "Patient", "Observant", "Enthusiastic"],
    strengths_ar: ["داعم", "موثوق", "صبور", "يقظ", "متحمس"],
    weaknesses_en: ["Overly humble", "Takes things personally", "Represses feelings", "Overloads themselves"],
    weaknesses_ar: ["متواضع للغاية", "يأخذ الأمور بشكل شخصي", "يكبت مشاعره", "يُثقل نفسه"],
    careers_en: ["Nurse", "Social Worker", "Teacher", "HR Manager", "Interior Designer"],
    careers_ar: ["ممرض", "أخصائي اجتماعي", "معلم", "مدير موارد بشرية", "مصمم داخلي"],
    famous_en: ["Mother Teresa", "Queen Elizabeth II", "Beyoncé"],
    color: "#F78FB3",
    emoji: "🛡️",
  },
  ESTJ: {
    type: "ESTJ",
    name_en: "The Executive",
    name_ar: "التنفيذي",
    tagline_en: "Excellent administrators, unsurpassed at managing things",
    tagline_ar: "مديرون ممتازون لا مثيل لهم في إدارة الأمور",
    description_en: "ESTJs are tradition-bound organizers who steer groups, institutions, and communities toward order.",
    description_ar: "التنفيذيون منظمون مرتبطون بالتقاليد يقودون المجموعات والمؤسسات والمجتمعات نحو النظام.",
    strengths_en: ["Dedicated", "Strong-willed", "Direct", "Patient", "Reliable"],
    strengths_ar: ["متفانٍ", "قوي الإرادة", "مباشر", "صبور", "موثوق"],
    weaknesses_en: ["Inflexible", "Uncomfortable with unconventional situations", "Judgmental", "Bossy"],
    weaknesses_ar: ["غير مرن", "غير مرتاح للمواقف غير التقليدية", "يصدر الأحكام", "متسلط"],
    careers_en: ["Manager", "School Principal", "Judge", "Financial Officer", "Police Officer"],
    careers_ar: ["مدير", "مدير مدرسة", "قاضي", "مسؤول مالي", "ضابط شرطة"],
    famous_en: ["Michelle Obama", "Lyndon B. Johnson", "Frank Sinatra"],
    color: "#45B7D1",
    emoji: "💼",
  },
  ESFJ: {
    type: "ESFJ",
    name_en: "The Consul",
    name_ar: "القنصل",
    tagline_en: "Extraordinarily caring, social and popular people",
    tagline_ar: "أشخاص بالغو الرعاية، اجتماعيون وشعبيون بشكل استثنائي",
    description_en: "ESFJs are warmhearted individuals who thrive when they're caring for others. They are natural community builders who value harmony.",
    description_ar: "القناصل أفراد طيبو القلب يزدهرون عندما يهتمون بالآخرين. إنهم بناة مجتمعات طبيعيون يقدرون الانسجام.",
    strengths_en: ["Strong practical skills", "Loyal", "Sensitive", "Warm", "Good at connecting"],
    strengths_ar: ["مهارات عملية قوية", "مخلص", "حساس", "دافئ", "جيد في التواصل"],
    weaknesses_en: ["Worried about status", "Inflexible", "Reluctant to improvise", "Vulnerable to criticism"],
    weaknesses_ar: ["قلق بشأن المكانة", "غير مرن", "متردد في الارتجال", "ضعيف أمام النقد"],
    careers_en: ["Teacher", "Social Worker", "Event Planner", "Nurse", "Office Manager"],
    careers_ar: ["معلم", "أخصائي اجتماعي", "منظم فعاليات", "ممرض", "مدير مكتب"],
    famous_en: ["Taylor Swift", "Jennifer Garner", "Bill Clinton"],
    color: "#FF8C69",
    emoji: "💛",
  },
  ISTP: {
    type: "ISTP",
    name_en: "The Virtuoso",
    name_ar: "العبقري",
    tagline_en: "Bold and practical experimenters, masters of tools",
    tagline_ar: "تجريبيون جريئون وعمليون، أسياد الأدوات",
    description_en: "ISTPs are observant artists, constantly experimenting and exploring the physical world. They are unpredictable and thrive in crisis.",
    description_ar: "العباقرة فنانون يقظون، يجربون ويستكشفون العالم المادي باستمرار. إنهم غير متوقعين ويزدهرون في الأزمات.",
    strengths_en: ["Optimistic", "Energetic", "Creative", "Practical", "Spontaneous"],
    strengths_ar: ["متفائل", "نشيط", "مبدع", "عملي", "تلقائي"],
    weaknesses_en: ["Stubborn", "Insensitive", "Private", "Easily bored", "Risky behavior"],
    weaknesses_ar: ["عنيد", "غير حساس", "منعزل", "يمل بسهولة", "سلوك محفوف بالمخاطر"],
    careers_en: ["Mechanic", "Engineer", "Pilot", "Programmer", "Forensic Scientist"],
    careers_ar: ["ميكانيكي", "مهندس", "طيار", "مبرمج", "عالم جنائي"],
    famous_en: ["Steve Jobs", "Bruce Lee", "Clint Eastwood"],
    color: "#A8E6CF",
    emoji: "🔧",
  },
  ISFP: {
    type: "ISFP",
    name_en: "The Adventurer",
    name_ar: "المغامر",
    tagline_en: "Flexible and charming artists, always ready to explore new things",
    tagline_ar: "فنانون مرنون وساحرون، دائمًا مستعدون لاستكشاف أشياء جديدة",
    description_en: "ISFPs are true artists, not necessarily in the sense of painting, but in their care for the senses, aesthetics, and all things beautiful.",
    description_ar: "المغامرون فنانون حقيقيون، ليس بالضرورة بمعنى الرسم، ولكن في اهتمامهم بالحواس والجماليات وكل الأشياء الجميلة.",
    strengths_en: ["Charming", "Sensitive to others", "Imaginative", "Passionate", "Curious"],
    strengths_ar: ["ساحر", "حساس للآخرين", "خيالي", "شغوف", "فضولي"],
    weaknesses_en: ["Fiercely independent", "Unpredictable", "Easily stressed", "Overly competitive"],
    weaknesses_ar: ["مستقل بشدة", "غير متوقع", "يُجهَد بسهولة", "تنافسي للغاية"],
    careers_en: ["Fashion Designer", "Photographer", "Musician", "Chef", "Veterinarian"],
    careers_ar: ["مصمم أزياء", "مصور", "موسيقي", "طاهٍ", "طبيب بيطري"],
    famous_en: ["Michael Jackson", "Britney Spears", "Lana Del Rey"],
    color: "#DDA0DD",
    emoji: "🎨",
  },
  ESTP: {
    type: "ESTP",
    name_en: "The Entrepreneur",
    name_ar: "المقاول",
    tagline_en: "Smart, energetic and very perceptive people, who truly enjoy living on the edge",
    tagline_ar: "أشخاص أذكياء ونشيطون وذو إدراك حاد، يستمتعون حقًا بالعيش على الحافة",
    description_en: "ESTPs are the ultimate action heroes. They live in the present moment, solving practical problems with hands-on experience.",
    description_ar: "المقاولون أبطال العمل الأمثل. يعيشون في اللحظة الحالية، يحلون المشكلات العملية بتجربة مباشرة.",
    strengths_en: ["Bold", "Rational", "Original", "Perceptive", "Direct"],
    strengths_ar: ["جريء", "عقلاني", "أصيل", "إدراكي", "مباشر"],
    weaknesses_en: ["Impatient", "Risk-prone", "Unstructured", "May miss the bigger picture"],
    weaknesses_ar: ["نفاد صبر", "عرضة للمخاطر", "غير منظم", "قد يفوته الصورة الكبيرة"],
    careers_en: ["Entrepreneur", "Paramedic", "Sales Manager", "Broker", "Detective"],
    careers_ar: ["رائد أعمال", "مسعف", "مدير مبيعات", "سمسار", "محقق"],
    famous_en: ["Donald Trump", "Ernest Hemingway", "Madonna"],
    color: "#F4A261",
    emoji: "🚀",
  },
  ESFP: {
    type: "ESFP",
    name_en: "The Entertainer",
    name_ar: "المسلّي",
    tagline_en: "Spontaneous, energetic and enthusiastic people, life is never boring around them",
    tagline_ar: "أشخاص تلقائيون ونشيطون ومتحمسون، الحياة لا تمل بوجودهم أبدًا",
    description_en: "ESFPs are vivacious entertainers who enjoy the spotlight. They are spontaneous, energetic, and always bring fun to the party.",
    description_ar: "المسلّون ممثلون حيويون يستمتعون بالأضواء. إنهم تلقائيون ونشيطون ودائمًا يجلبون المتعة للحفلة.",
    strengths_en: ["Bold", "Original", "Aesthetic", "Showmanship", "Practical"],
    strengths_ar: ["جريء", "أصيل", "جمالي", "براعة في التمثيل", "عملي"],
    weaknesses_en: ["Sensitive", "Conflict-averse", "Easily bored", "Poor long-term planners"],
    weaknesses_ar: ["حساس", "يتجنب الصراع", "يمل بسهولة", "ضعيف في التخطيط بعيد المدى"],
    careers_en: ["Actor", "Event Planner", "Fashion Designer", "Tour Guide", "Bartender"],
    careers_ar: ["ممثل", "منظم فعاليات", "مصمم أزياء", "مرشد سياحي", "نادل"],
    famous_en: ["Marilyn Monroe", "Elvis Presley", "Justin Bieber"],
    color: "#FF6B6B",
    emoji: "🎉",
  },
};
