// ─── MBTI Question Bank ──────────────────────────────────────────────────────
// 40 questions, 10 per dimension (EI, SN, TF, JP)
// value 1 = strongly toward E/S/T/J, value 5 = strongly toward I/N/F/P
// positiveDirection: the pole a "Strongly Agree" (value 1) maps to

import type { TestQuestion } from "@/types";

export const questions: Omit<TestQuestion, "_id">[] = [
  // ── E/I Dimension ──────────────────────────────────────────────────────────
  {
    dimension: "EI",
    positiveDirection: "E",
    order: 1,
    text_en: "I feel energized after spending time with a large group of people.",
    text_ar: "أشعر بالنشاط بعد قضاء الوقت مع مجموعة كبيرة من الناس.",
  },
  {
    dimension: "EI",
    positiveDirection: "E",
    order: 2,
    text_en: "I enjoy meeting new people and strike up conversations easily.",
    text_ar: "أستمتع بمقابلة أشخاص جدد وأبدأ المحادثات بسهولة.",
  },
  {
    dimension: "EI",
    positiveDirection: "E",
    order: 3,
    text_en: "I prefer to think out loud rather than reflect quietly before speaking.",
    text_ar: "أفضل التفكير بصوت عالٍ بدلاً من التأمل الهادئ قبل الكلام.",
  },
  {
    dimension: "EI",
    positiveDirection: "E",
    order: 4,
    text_en: "I often initiate social activities and gatherings.",
    text_ar: "أبادر في كثير من الأحيان بإطلاق الأنشطة الاجتماعية والتجمعات.",
  },
  {
    dimension: "EI",
    positiveDirection: "E",
    order: 5,
    text_en: "I feel comfortable being the center of attention in social situations.",
    text_ar: "أشعر بالراحة عندما أكون محور الاهتمام في المواقف الاجتماعية.",
  },
  {
    dimension: "EI",
    positiveDirection: "I",
    order: 6,
    text_en: "I need significant alone time to recharge after social interactions.",
    text_ar: "أحتاج إلى وقت كافٍ بمفردي لإعادة شحن طاقتي بعد التفاعلات الاجتماعية.",
  },
  {
    dimension: "EI",
    positiveDirection: "I",
    order: 7,
    text_en: "I prefer deep one-on-one conversations over large group discussions.",
    text_ar: "أفضل المحادثات العميقة الفردية على النقاشات الجماعية الكبيرة.",
  },
  {
    dimension: "EI",
    positiveDirection: "I",
    order: 8,
    text_en: "I usually think carefully before speaking or acting.",
    text_ar: "عادةً ما أفكر بعناية قبل الكلام أو التصرف.",
  },
  {
    dimension: "EI",
    positiveDirection: "I",
    order: 9,
    text_en: "I prefer to have a small circle of close friends rather than many acquaintances.",
    text_ar: "أفضل وجود دائرة صغيرة من الأصدقاء المقربين بدلاً من عدد كبير من المعارف.",
  },
  {
    dimension: "EI",
    positiveDirection: "I",
    order: 10,
    text_en: "I often find social events draining and prefer quiet evenings at home.",
    text_ar: "أجد الفعاليات الاجتماعية مُجهِدة في كثير من الأحيان وأفضل الأمسيات الهادئة في المنزل.",
  },

  // ── S/N Dimension ──────────────────────────────────────────────────────────
  {
    dimension: "SN",
    positiveDirection: "S",
    order: 11,
    text_en: "I focus on facts and concrete details rather than abstract concepts.",
    text_ar: "أركز على الحقائق والتفاصيل الملموسة بدلاً من المفاهيم المجردة.",
  },
  {
    dimension: "SN",
    positiveDirection: "S",
    order: 12,
    text_en: "I trust experience and what has worked in the past more than new theories.",
    text_ar: "أثق بالتجربة وبما نجح في الماضي أكثر من النظريات الجديدة.",
  },
  {
    dimension: "SN",
    positiveDirection: "S",
    order: 13,
    text_en: "I prefer step-by-step instructions rather than figuring things out myself.",
    text_ar: "أفضل التعليمات خطوة بخطوة بدلاً من اكتشاف الأمور بنفسي.",
  },
  {
    dimension: "SN",
    positiveDirection: "S",
    order: 14,
    text_en: "I pay close attention to sensory details in my environment.",
    text_ar: "أولي اهتمامًا وثيقًا للتفاصيل الحسية في بيئتي.",
  },
  {
    dimension: "SN",
    positiveDirection: "S",
    order: 15,
    text_en: "I prefer practical, realistic solutions over theoretical ones.",
    text_ar: "أفضل الحلول العملية والواقعية على النظرية.",
  },
  {
    dimension: "SN",
    positiveDirection: "N",
    order: 16,
    text_en: "I often think about future possibilities and what could be.",
    text_ar: "كثيرًا ما أفكر في الاحتمالات المستقبلية وما يمكن أن يكون.",
  },
  {
    dimension: "SN",
    positiveDirection: "N",
    order: 17,
    text_en: "I enjoy exploring abstract ideas and theoretical concepts.",
    text_ar: "أستمتع باستكشاف الأفكار المجردة والمفاهيم النظرية.",
  },
  {
    dimension: "SN",
    positiveDirection: "N",
    order: 18,
    text_en: "I often see patterns and connections that others miss.",
    text_ar: "غالبًا ما أرى أنماطًا وروابط يفوتها الآخرون.",
  },
  {
    dimension: "SN",
    positiveDirection: "N",
    order: 19,
    text_en: "I am drawn to innovative ideas and unconventional approaches.",
    text_ar: "أنجذب إلى الأفكار المبتكرة والمناهج غير التقليدية.",
  },
  {
    dimension: "SN",
    positiveDirection: "N",
    order: 20,
    text_en: "I trust my intuition more than empirical evidence when making decisions.",
    text_ar: "أثق بحدسي أكثر من الأدلة التجريبية عند اتخاذ القرارات.",
  },

  // ── T/F Dimension ──────────────────────────────────────────────────────────
  {
    dimension: "TF",
    positiveDirection: "T",
    order: 21,
    text_en: "I make decisions based on logic and objective analysis rather than feelings.",
    text_ar: "أتخذ القرارات بناءً على المنطق والتحليل الموضوعي بدلاً من المشاعر.",
  },
  {
    dimension: "TF",
    positiveDirection: "T",
    order: 22,
    text_en: "I tend to prioritize truth and accuracy over tact and diplomacy.",
    text_ar: "أميل إلى إعطاء الأولوية للحقيقة والدقة على اللباقة والدبلوماسية.",
  },
  {
    dimension: "TF",
    positiveDirection: "T",
    order: 23,
    text_en: "I can remain calm and detached when making difficult decisions.",
    text_ar: "يمكنني البقاء هادئًا ومنفصلًا عند اتخاذ قرارات صعبة.",
  },
  {
    dimension: "TF",
    positiveDirection: "T",
    order: 24,
    text_en: "I value competence and efficiency more than harmony and feelings.",
    text_ar: "أقدر الكفاءة والفاعلية أكثر من الانسجام والمشاعر.",
  },
  {
    dimension: "TF",
    positiveDirection: "T",
    order: 25,
    text_en: "I believe critical feedback is more helpful than empty encouragement.",
    text_ar: "أعتقد أن التغذية الراجعة الانتقادية أكثر فائدة من التشجيع الفارغ.",
  },
  {
    dimension: "TF",
    positiveDirection: "F",
    order: 26,
    text_en: "I often make decisions based on how they will affect others' feelings.",
    text_ar: "كثيرًا ما أتخذ القرارات بناءً على كيفية تأثيرها على مشاعر الآخرين.",
  },
  {
    dimension: "TF",
    positiveDirection: "F",
    order: 27,
    text_en: "I am highly empathetic and easily understand how others are feeling.",
    text_ar: "أنا شديد التعاطف وأفهم بسهولة كيف يشعر الآخرون.",
  },
  {
    dimension: "TF",
    positiveDirection: "F",
    order: 28,
    text_en: "Maintaining harmony in relationships is very important to me.",
    text_ar: "الحفاظ على الانسجام في العلاقات مهم جدًا بالنسبة لي.",
  },
  {
    dimension: "TF",
    positiveDirection: "F",
    order: 29,
    text_en: "I often put others' needs before my own.",
    text_ar: "كثيرًا ما أضع احتياجات الآخرين قبل احتياجاتي.",
  },
  {
    dimension: "TF",
    positiveDirection: "F",
    order: 30,
    text_en: "I find it difficult to deliver criticism without worrying about hurting feelings.",
    text_ar: "أجد صعوبة في تقديم النقد دون القلق من إيذاء مشاعر الآخرين.",
  },

  // ── J/P Dimension ──────────────────────────────────────────────────────────
  {
    dimension: "JP",
    positiveDirection: "J",
    order: 31,
    text_en: "I prefer having a clear plan before starting a project.",
    text_ar: "أفضل وجود خطة واضحة قبل بدء المشروع.",
  },
  {
    dimension: "JP",
    positiveDirection: "J",
    order: 32,
    text_en: "I feel uncomfortable when things are left unresolved or unfinished.",
    text_ar: "أشعر بعدم الراحة عندما تُترك الأمور دون حل أو غير مكتملة.",
  },
  {
    dimension: "JP",
    positiveDirection: "J",
    order: 33,
    text_en: "I rely on schedules and deadlines to organize my work and life.",
    text_ar: "أعتمد على الجداول الزمنية والمواعيد النهائية لتنظيم عملي وحياتي.",
  },
  {
    dimension: "JP",
    positiveDirection: "J",
    order: 34,
    text_en: "I prefer to make decisions promptly rather than leave options open.",
    text_ar: "أفضل اتخاذ القرارات فورًا بدلاً من إبقاء الخيارات مفتوحة.",
  },
  {
    dimension: "JP",
    positiveDirection: "J",
    order: 35,
    text_en: "I keep my living and work spaces tidy and organized.",
    text_ar: "أحتفظ بأماكن معيشتي وعملي مرتبة ومنظمة.",
  },
  {
    dimension: "JP",
    positiveDirection: "P",
    order: 36,
    text_en: "I prefer to keep my options open rather than commit to a fixed plan.",
    text_ar: "أفضل إبقاء خياراتي مفتوحة بدلاً من الالتزام بخطة محددة.",
  },
  {
    dimension: "JP",
    positiveDirection: "P",
    order: 37,
    text_en: "I enjoy spontaneous activities and last-minute changes.",
    text_ar: "أستمتع بالأنشطة التلقائية والتغييرات في اللحظة الأخيرة.",
  },
  {
    dimension: "JP",
    positiveDirection: "P",
    order: 38,
    text_en: "I work better under pressure and close to deadlines.",
    text_ar: "أعمل بشكل أفضل تحت الضغط وقرب المواعيد النهائية.",
  },
  {
    dimension: "JP",
    positiveDirection: "P",
    order: 39,
    text_en: "I am comfortable starting a task before I have all the information.",
    text_ar: "أشعر بالراحة في بدء مهمة قبل حصولي على جميع المعلومات.",
  },
  {
    dimension: "JP",
    positiveDirection: "P",
    order: 40,
    text_en: "I find strict routines and rigid schedules limiting and stifling.",
    text_ar: "أجد الروتين الصارم والجداول الجامدة مقيّدة وخانقة.",
  },
];
